# devnet

[package]
name = "Toma"
version = "0.1.0"
edition = "2024.beta"
published-at = "0x0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/devnet" }

[addresses]
# when you want to deploy Toma, this must be set to 0x0
# when you want to deploy Atoma, this must equal published-at
toma = "0x0"
