#!/bin/bash

#
# Invokes the CLI binary with the given arguments.
#
# $ ./cli help
#

function abs_path_to_git_root_dir() {
    # Recursively find the repo root directory so that this script can be called
    # from anywhere

    if [ -d "atoma-contracts" ]; then
        echo "$(pwd)/atoma-contracts"
    elif [ "$(pwd)" == "/" ]; then
        echo "No atoma-contracts directory found"
        exit 1
    else
        cd ..
        abs_path_to_git_root_dir
    fi
}

entrance_dir=$(pwd)
root_dir=$(abs_path_to_git_root_dir)

cd $root_dir/sui/cli
cargo run -- --wallet ~/.sui/sui_config/client.yaml $@

# leave the caller where they started
cd $entrance_dir
