#!/bin/bash

#
# Airdrops bunch of TOMA tokens to the caller.
# Provide the faucet object ID as the first argument, or have it present
# as an environment variable FAUCET_ID.
#

set -e

# Function to load .env file if it exists
load_env_file() {
    local file=$1
    if [ -f "$file" ]; then
        set -o allexport
        source "$file"
        set +o allexport
    fi
}

faucet="${1:-$FAUCET_ID}"

if [ -z "${faucet}" ]; then
    # faucet does not exist, load .env. Don't do this by default, only if
    # the caller did not provide the faucet ID as an argument, otherwise we
    # might bring in some other ENV vars and mess with the caller's script.
    load_env_file "../../.env"
    load_env_file "../.env"
    load_env_file ".env"
    faucet="${FAUCET_ID}"

    if [ -z "${faucet}" ]; then
        echo "Usage: $0 <faucet ID>"
        exit 1
    fi
fi

faucet_package=$(
    sui client object "${faucet}" --json |
        jq ".type" -rc |
        grep -oP '^[^:]+'
)

if [ -z "${faucet_package}" ]; then
    echo "Cannot get package of faucet object ${faucet}"
    exit 1
fi

echo

sui client call \
    --package "${faucet_package}" --module "toma" --function "faucet" \
    --gas-budget 10000000 \
    --args "${faucet}" 10000000 || exit 1

echo
